version: 3.8;

services:
    updatecerts:
        image: vjedev/certupdater:latest
        volumes:
            - certs:/certs
            - mysqlconf:/mysqlconf

    landingpage:
        image: vjedev/landingpage:latest
        volumes:
            - ./websites:/websites

    databaseimportexport:
        image: vjedev/database-import-export:latest
        volumes:
            - ./websites:/websites
        depends_on:
            - mysql

    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - certs:/certs
            - ./websites:/websites
        depends_on:
            - updatecerts

    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./websites:/websites

    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'v.je'
            MYSQL_USER: 'v.je'
            MYSQL_PASSWORD: 'v.je'
        volumes:
            - mysqldata:/var/lib/mysql
            - certs:/ssl
            - mysqlconf:/etc/mysql/conf.d/
        ports:
            - 3306:3306

    phpmyadmin:  # ✅ Added phpMyAdmin service here
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - "8080:80"  # phpMyAdmin will be available at http://localhost:8080
        environment:
            PMA_HOST: mysql  # It connects to the MySQL container
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: 'v.je'
        depends_on:
            - mysql

    phpunit:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        working_dir: /websites/default
        entrypoint: 'vendor/bin/phpunit'
        volumes:
            - ./websites:/websites
        profiles:
            - phpunit

    composer:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        working_dir: /websites/default
        entrypoint: /usr/bin/composer
        volumes:
            - ./websites:/websites
        profiles:
            - composer

    maildev:
        image: maildev/maildev:latest

volumes:
    mysqldata: {}
    certs: {}
    mysqlconf: {}